# Generated by Django 4.1.7 on 2023-03-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('text', models.CharField(max_length=2000)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('reverse_score', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('internal_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
