# Generated by Django 4.1.7 on 2023-03-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0004_question_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Question categories'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
