# Generated by Django 4.1.7 on 2023-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0005_alter_questioncategory_options_questionnaire_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
