# Generated by Django 4.1.7 on 2023-03-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0006_questionnaire_description_questionnaire_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
