# Generated by Django 4.1.7 on 2023-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0009_rename_user_respondant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondant',
            name='fingerprint',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
