# Generated by Django 4.1.7 on 2023-04-08 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0011_alter_respondant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respondant',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
