# Generated by Django 4.1.7 on 2023-04-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0012_respondant_date_respondant_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondant',
            name='last_activity',
        ),
    ]
