# Generated by Django 4.1.7 on 2023-04-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0013_remove_respondant_last_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respondant',
            new_name='Respondent',
        ),
        migrations.RenameField(
            model_name='questionnaireresponse',
            old_name='respondant',
            new_name='respondent',
        ),
    ]
