# Generated by Django 4.1.7 on 2023-04-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0016_questionnaire_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('internal_name', models.CharField(max_length=100, unique=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('scores', models.TextField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maia_v2.questionnaire')),
            ],
        ),
    ]
