# Generated by Django 4.1.7 on 2023-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0017_questionnairedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairedata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
