# Generated by Django 4.1.7 on 2023-04-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0018_questionnairedata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairedata',
            name='paper_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
