# Generated by Django 4.1.7 on 2023-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maia_v2', '0019_questionnairedata_paper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
